---
# tasks file for roles/deny-port-3000-externally
- name: Ensure UFW is installed
  apt:
    name: ufw
    state: present

- name: Allow OpenSSH
  ufw:
    rule: allow
    name: OpenSSH

- name: Allow traffic on port 80
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Deny external access to port 3000
  ufw:
    rule: deny
    port: 3000
    proto: tcp

- name: Allow local access to port 3000
  ufw:
    rule: allow
    from: 127.0.0.1
    port: 3000
    proto: tcp

- name: Enable UFW
  ufw:
    state: enabled