---
# tasks file for roles/nginx
- name: Add the Nginx official repository key
  ansible.builtin.apt_key:
    url: http://nginx.org/keys/nginx_signing.key
    state: present

- name: Add the Nginx official repository
  ansible.builtin.apt_repository:
    repo: "deb http://nginx.org/packages/ubuntu/ {{ ansible_distribution_release }} nginx"
    state: present


- name: Install Nginx 1.26
  apt:
    name: nginx=1.26.0-1~{{ ansible_distribution_release }}
    state: present
  register: install_nginx_output 


- name: Append install Nginx stdout to log
  shell: |
    echo "{{ install_nginx_output.stdout }}" >> "{{ log_stdout_path }}"
  when: install_nginx_output.stdout is defined and install_nginx_output.stdout != ""

- name: Append install Nginx stderr to log
  shell: |
    echo "{{ install_nginx_output.stderr }}" >> "{{ log_stderr_path }}"
  when: install_nginx_output.stderr is defined and install_nginx_output.stderr != ""


- name: Remove default Nginx site configuration
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify:
    - restart nginx

- name: Copy custom Nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  notify:
    - restart nginx





