- name: Setup application environment
  hosts: hng
  become: yes
  vars:
    git_branch_name: "devops"
    pg_cred_path: "/var/secrets/pg_pw.txt"
    app_port: 3000
    nginx_http_port: 80
    log_stderr_path: "/var/log/stage_5b/error.log"
    log_stdout_path: "/var/log/stage_5b/out.log"
    deployment_user: "hng"
    git_repo_url: "https://github.com/hngprojects/hng_boilerplate_python_fastapi_web.git"
    local_repo_path: "/opt/stage_5b"
    virtual_env: "venv"
    pg_database_name: "ben_database"
    pg_admin_user: "admin"
    pg_admin_password: "password123"

  roles:
    - common
    - clone-repo
    - dependencies-and-packages
    - virtual-environment
    - postgres
    - app
    - deny-port-3000-externally
    - nginx
