---
# tasks file for roles/app
- name: Ensure the remote_tmp directory exists with correct permissions
  file:
    path: /tmp/.ansible-hng/tmp
    state: directory
    mode: '0777'
    owner: root
    group: root

- name: Clone the repository
  git:
    repo: "{{ git_repo_url }}"
    dest: "{{ local_repo_path }}"
    version: "{{ git_branch_name }}"
    force: yes
  become_user: "{{ deployment_user }}"
  register: git_output

- name: Debug git_output
  debug:
    var: git_output

- name: Log git clone stdout
  copy:
    content: "{{ git_output.after }}"
    dest: "{{ log_stdout_path }}"
  when: git_output.after is defined and git_output.after != ""

- name: Log git clone stderr
  copy:
    content: "{{ git_output.before }}"
    dest: "{{ log_stderr_path }}"
  when: git_output.before is defined and git_output.before != ""
