---
# tasks file for roles/nginx

- name: Ensure python3.12-venv is installed
  ansible.builtin.apt:
    name: python3.12-venv
    state: present
    update_cache: yes


# Highlighted update starts here
- name: Ensure python3-psycopg2 is installed
  ansible.builtin.apt:
    name: python3-psycopg2
    state: present
    update_cache: yes
    